- errors/errors.go
- identity/authorization.go
> Add IsAuthorized endpoint

- .github/workflows/changelog.yaml
> ci: switch to identity workload provider

- .github/workflows/changelog.yaml
Release pipeline was failing due to missing pull-request scope as well as content write permissions.
> ci: add correct permissions for the pipeline

- .github/CODEOWNERS
- .github/renovate.json
- .github/workflows/pr-test.yaml
> Updates with codeowners and renovate

- .golangci.yml
- config/config_client.go
- config/utilities.go
- errors/errors.go
- examples/config/cmd/root.go
- gen/indykite/identity/v1beta1/attributes.ext.go
- grpc/config/credentials.go
- grpc/config/tls.go
- grpc/option.go
- grpc/transport.go
- identity/digital_twin.go
- identity/identity_client.go
- ingest/ingest_client.go
Improved linter settings as there is newer version of linter with new rules
> chore: improve linter

- .github/workflows/go-lint-check.yaml
- .github/workflows/pr-test.yaml
- .golangci.yml
- config/service_account.go
- examples/config/cmd/service_account.go
> feat: add service account functions

- .github/workflows/changelog.yaml
> fix: remove unrequired pat token and clickup step

- commitlint.config.js
none
Based on Slack discussion and https://www.notion.so/indykite/Commit-lint-configuration-8ee3971f7c394a9fb60cbe9a2cc1e0b5
> ci: improve commitlint rules

- release-please-config.json
> ci: add missing release please config

- .github/workflows/changelog.yaml
- examples/identity/cmd/invitation.go
> ci: fix release pipeline

- README.md
- examples/oauth2/README.md
- examples/oauth2/cmd.go
- examples/oauth2/cmd/root.go
- examples/oauth2/cmd/token.go
- grpc/config/credentials.go
- grpc/internal/settings.go
- grpc/jwt/jwt.go
- grpc/jwt/jwt_test.go
- oauth2/example_test.go
- oauth2/oauth2_suite_test.go
- oauth2/token.go
- oauth2/token_test.go
This PR adds
* A function to generate a refreshable token that can be used to make authenticated requests, for instance to the Knowledge API
* A function to generate a client, authenticated with this refreshable token, which can be used to call the Knowledge API
* Some cleanup in relation to the above
When this is approved and merged, I will create tickets to implement the same functionality in the Node and Python SDKs.
> implement token and http client functions

- responsible_disclosure.md
Sync with https://www.indykite.com/responsible-disclosure-policy
responsible_disclosure.md
Sync with https://www.indykite.com/responsible-disclosure-policy
> docs: update responsible disclosure

- .github/workflows/pr-test.yaml
- go.mod
- go.sum
> chore: fix invalid dependency compatibility of tools

- config/service_account_credentials.go
- config/service_account_credentials_test.go
- examples/config/cmd/service_account_credential.go
> feat: add service account credentials methods

- config/application_agent_credentials_test.go
- config/application_agent_test.go
- config/application_space_test.go
- config/application_test.go
- config/container_configuration_test.go
- config/customer_test.go
- config/service_account_credentials_test.go
- config/service_account_test.go
Closing ENG-1541
- add tests for spaces
- add tests for application, application agent, application agent credential
- add tests for service account, service account credential
- add tests for containers
> test: config unit tests

- .github/workflows/changelog.yaml
> ci: fix typo in files to change

- authorization/authorization_suite_test.go
- authorization/client.go
- authorization/client_test.go
- authorization/is_authorized_test.go
- authorization/what_authorized_test.go
- authorization/who_authorized_test.go
Closing ENG-1601
- add unit tests for authorization
> feat: add authorization tests

- examples/ingest/cmd/root.go
- examples/ingest/cmd/stream_retry.go
- ingest/ingest_retry_client.go
- ingest/ingest_test.go
- ingest/stream_records.go
Retry stream client for when streams go down.
Link to issue: https://indykite.atlassian.net/browse/ENG-950
> feat: add retry stream client

- .github/workflows/pr-test.yaml
- GNUmakefile
- authorization/authorization_integration_test.go
- commitlint.config.js
- go.mod
- go.sum
- ingest/ingest_integration_test.go
- test/constants.go
- test/integration_client.go
Closing ENG-1760
- add IKG integration tests
- add KBAC integration tests
> test: add integration tests for ikg and kbac

- config/config_node_test.go
> feat: remove readid config node

- codecov.yaml
- examples/helpers/README.md
- examples/helpers/cmd.go
- examples/helpers/cmd/delete.go
- examples/helpers/cmd/root.go
- helpers/doc.go
- helpers/example_test.go
- helpers/helpers.go
- helpers/helpers_client.go
- helpers/helpers_suite_test.go
Closing ENG-1939
creation of a helpers package
> feat: add delete all KG nodes helper

- .github/workflows/pr-test.yaml
- README.md
Implementing ENG-2506
- add worflow-dispatch for BE people to be able to run the tests manually
> feat: add worflow dispatch in actions

- .github/workflows/pr-test.yaml
- README.md
Implementing ENG-2526
add workflow dispatch to test conditions
> test: add workflow dispatch to test conditions

- release-please-config.json
> ci: add missing attribute to release please config

- .github/workflows/changelog.yaml
- README.md
> feat: change value in changelog

- GNUmakefile
> test: add traces in authz tests

- GNUmakefile
implement ENG-3438
- update makefile
> test: lower  execution time of integration tests

- ingest/ingest_integration_test.go
implement ENG-3438
- ignore ingest integration tests
> test: ignore ingest integration tests

- .github/workflows/pr-test.yaml
- authorization/authorization_integration_test.go
> feat: remove tests from pipeline

- .github/workflows/pr-test.yaml
- authorization/authorization_integration_test.go
- ingest/ingest_integration_test.go
- test/constants.go
> test: put integration back

- .deepsource.toml
> chore: add deepsource file

- .deepsource.toml
> test: specify test files in deepsource

- tda/data_access_integration_test.go
- tda/data_access_test.go
implement ENG-3799
- remove tda tests temporarily
> feat: remove tda tests temporarily

- GNUmakefile
- buf.openapi.gen.yaml
implement ENG-3999
change go version
> feat: change go version

- examples/helpers/cmd/entitymatching.go
- helpers/helper_entitymatching.go
implement ENG-4752
- fix a bug
- minor modifications
> fix: modify helpers for entitymatching

- config/config_integration_test.go
- config/config_node_test.go
- examples/config/cmd/entity_matching_pipeline.go
- test/constants.go
ENG-5051
Fix for bug https://indykite.atlassian.net/browse/ENG-5051 broke the sdk tests
> fix: align update EM pipeline request to new specs

- config/config_integration_test.go
- ingest/ingest_record.go
implement ENG-4927
- add loop to delete AppSpace in EM test
> fix: add loop to delete AppSpace

- authorization/authorization_integration_test.go
implement ENG-5161
- remove tests on bad resolver
> feat: remove bad resolver tests

- go.work.sum
- knowledge/knowledge_read_integration_test.go
implement ENG-4088
remove system lables in IKG api queries in lists
> feat: remove system labels in queries

- grpc/pool.go
> fix: fix pool issue

- config/config_node_test.go
- config/config_request.go
- examples/config/cmd/authorization.go
- examples/config/cmd/capture_pipeline.go
- go.work.sum
implement ENG-6025
- add capture pipeline config
- add tests
> feat: add capture pipeline configs

- config/config_integration_test.go
- config/config_node_test.go
- examples/config/cmd/event_config.go
https://indykite.atlassian.net/browse/ENG-6060
> fix: fix broker endpoint format
